### ISSUE TITLE
pytorch 版本？

### ISSUE THREAD

**Issue by TomSirLiu** [DataXujing/YOLO-v5#16]
```
python3 train.py --img-size 640 --batch-size 16 --epochs 300 --data ./data/my.yaml --cfg ./models/my_yolov5x.yaml --weights weights/yolov5s.pt --device 1
```

错误1：AttributeError: module 'torch.nn' has no attribute 'Hardswish'，这是只有torch 1.6.0 才有的模块
错误2：torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set' 根据 https://github.com/ultralytics/yolov5/issues/58，得装torch 1.5.1

所以我要装哪个版本？

**Comment by DataXujing** [comment]
你如果clone的本项目，可以按照README的版本运行时没问题的，你如果clone的是官方最新的repo,请参照官方要求的环境运行。

**Comment by TomSirLiu** [comment]
> 你如果clone的本项目，可以按照README的版本运行是没问题的，
> 
> ```
> # torch==1.3.0
> # torchvision==0.4.1
> ```
> 
> 你如果clone的是官方最新的repo,请参照官方要求的环境运行。

感谢！！教程中的git clone到的是官方repo，之前没细看，抱歉
