### ISSUE TITLE
AttributeError: 'function' object has no attribute 'names'

### ISSUE THREAD

**Issue by AcodeC** [DataXujing/YOLO-v5#17]
在我已经训练完自己的数据集推理的时候，使用的是best.pt，结果出现了这个问题
  File "detect.py", line 164, in <module>
    detect()
  File "detect.py", line 48, in detect
    names = model.names if hasattr(model, 'names') else model.modules.names
AttributeError: 'function' object has no attribute 'names'

你能告诉我怎么解决吗？谢谢

**Comment by DataXujing** [comment]
请参考：
https://github.com/DataXujing/YOLO-v5/issues/9

**Comment by chunhui-zhang** [comment]
用detect.py进行测试的时候也遇到类似的问题，使用了预训练权重yolov5s.pt（27.18M），生成的best.pt（52.87M）


Traceback (most recent call last):
  File "detect.py", line 171, in <module>
    detect()
  File "detect.py", line 51, in detect
    names = model.names if hasattr(model, 'names') else model.modules.names
AttributeError: 'function' object has no attribute 'names'

**Comment by chunhui-zhang** [comment]
保存的best.pt权重似乎没有存变量名：names. 我的解决方式如下：

File "detect.py", line 51
 # names = model.names if hasattr(model, 'names') else model.modules.names
替换为
names = [‘class_0_name’,  ‘class_1_name’, ...]
