### ISSUE TITLE
大佬你好，可以分享一下resnet101的模型吗

### ISSUE THREAD

**Issue by Ritian-Li** [DataXujing/YOLO-v5#25]
万分感激

**Comment by Ritian-Li** [comment]
还有我不太懂为什么detect里面还有个分类的模型，我没有使用它也是有正确的分类，烦请大佬解惑有下
![image](https://user-images.githubusercontent.com/60093100/104395388-98f1eb00-5583-11eb-800e-565e45ce0c65.png)

**Comment by Ritian-Li** [comment]
还有我不太懂为什么detect里面还有个分类的模型，我没有使用它也是有正确的分类，烦请大佬解惑有下
![Uploading image.png…]()

**Comment by DataXujing** [comment]
这个是做第二个阶段对框进行二次分类用的，分类精度OK的话，不需要该模型。直接把classifier这个参数关掉就OK了。

**Comment by Ritian-Li** [comment]
> 这个是做第二个阶段对框进行二次分类用的，分类精度OK的话，不需要该模型。直接把classifier这个参数关掉就OK了。

谢谢大佬！
